# Generated by Django 4.2.13 on 2024-06-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reserva", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="petshop",
            options={"verbose_name": "Petshop", "verbose_name_plural": "Petshops"},
        ),
    ]
