# Generated by Django 4.2.13 on 2024-06-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("email", models.EmailField(max_length=100, verbose_name="E-mail")),
                (
                    "assunto",
                    models.CharField(
                        choices=[
                            ("banho", "Serviço de Banho"),
                            ("atendimento", "Atendimento ao Cliente"),
                            ("infraestrutura", "Instalações e Limpeza"),
                            ("preco", "Preços e Transparência"),
                            ("outro", "Outro"),
                        ],
                        default="todos",
                        max_length=20,
                        verbose_name="Assunto",
                    ),
                ),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                (
                    "data",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data Envio"),
                ),
                (
                    "lido",
                    models.BooleanField(blank=True, default=False, verbose_name="Lido"),
                ),
            ],
            options={
                "verbose_name": "Formulário de Contato",
                "verbose_name_plural": "Formulários de Contatos",
                "ordering": ["-data"],
            },
        ),
    ]
